language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - PHPUNIT_FLAGS="-v"

matrix:
  fast_finish: true
  include:
      # Test the latest stable release
    - php: 7.2
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"
    - php: 7.3
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
  # To be removed when this issue will be resolved: https://github.com/composer/composer/issues/5355
  - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --prefer-dist --no-interaction --prefer-stable --quiet; fi
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction --dev

script:
  - composer validate --strict --no-check-lock
  # simple-phpunit is the PHPUnit wrapper provided by the PHPUnit Bridge component and
  # it helps with testing legacy code and deprecations (composer require symfony/phpunit-bridge)
  - ./vendor/bin/phpunit $PHPUNIT_FLAGS
  - coverage report --fail-under=30
