services:
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Obblm\Core\:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Ressources,Tests,ObblmCoreBundle.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  Obblm\Core\Controller\:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  Obblm\Core\Routing\RouteAutoloader:
    autowire: true

  Obblm\Core\Helper\Rule\RuleHelperInterface:
    alias: Obblm\Core\Helper\Rule\BaseRule

  Obblm\Core\Routing\ObblmExtraLoader:
    arguments: [ '@Obblm\Core\Routing\RouteAutoloader' ]
    tags: [ routing.loader ]
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

