<?php

namespace Obblm\Core\Form\Team;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;

class InducementType extends AbstractType
{
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $options['data'] = $form->getData();
        $view->vars['value'] = $form->getData();
        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    }

    public function getParent()
    {
        return ChoiceType::class;
    }

    public function getBlockPrefix()
    {
        return 'obblm_inducement_choice';
    }
}
